### ISSUE TITLE
--all argument fails to run

### ISSUE THREAD

**Issue by disdi** [peterbay/sysinfo#1]
**--all** argument currently fails with error that buffer is not big enough for all the columns as shown below-

`saksinh@cmtcleu60844879:~/sysinfo$ python3 sysinfo.py --all
['ro', 'ra', 'ssz', 'bsz', 'startsec', 'size', 'device']
[4, 4, 5, 5, 10, 6, 6]
['name', 'pid', 'process', 'user', 'connection', 'unit', 'session', 'description']
[52, 7, 17, 17, 15, 27, 9, 11]
Traceback (most recent call last):
  File "sysinfo.py", line 190, in <module>
    main(sys.argv)
  File "sysinfo.py", line 187, in main
    run (args)
  File "sysinfo.py", line 140, in run
    parsed = parser(result.get('stdout', None), result.get('stderr', None))
  File "modules/busctl.py", line 7, in parser
    output = parseTable(stdout)
  File "modules/sysinfo_lib.py", line 71, in parseTable
    cols = unpack(packTemplate, bytes(line + (' ' * (totalLength - len(line))), 'utf-8'))
struct.error: unpack requires a buffer of 1168 bytes
`

**Comment by peterbay** [comment]
Buffer increased from value 1024 to 8192. Can you try it again?

**Comment by disdi** [comment]
It works now.
